### ISSUE TITLE
Deprecation warning during compilation on Android 10 (API 29)

### ISSUE THREAD

**Issue by TatsuUkraine** [mogol/flutter_secure_storage#162]
Deprecation warning during compilation on Android

```
Note: ..../.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.4/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale ru-UA)
    • Flutter version 1.20.4 at ....
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at .....
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Steps to reproduce**
- Run `flutter clean`
- build an application for Android

**Comment by 0biWanKenobi** [comment]
Can confirm, this happens

**Comment by CristianTorrado** [comment]
Hi i have the same issue i think you must to update the Android implementation to support the last update of Android platform, please i need this update soon. 

Have you a plan for this update soon ?

**Comment by Lukiya** [comment]
Same issue.

**Comment by yekkaplan** [comment]
I have same issue

**Comment by xbrunosousa** [comment]
Same here.

**Comment by RounakTadvi** [comment]
Same here.

**Comment by Emisoft12** [comment]
Same issue here and it work well on debug not in release mode

**Comment by Banzyme** [comment]
Also had to downgrade my target sdk version to version 28 in the meantime
................Error................
..
Note: /home/endeea/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.

**Comment by TatsuUkraine** [comment]
@mogol any update on this?

**Comment by 0biWanKenobi** [comment]
While we wait, [this fork](https://github.com/0biWanKenobi/flutter_secure_storage/tree/patch-1) I created should fix most if not all the deprecation warnings

**Comment by KDCinfo** [comment]
I downgraded to `3.3.3`, but then also had to manually delete the `3.3.5` folder from: `C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.5`.

**Comment by josechagas** [comment]
Same problem

**Comment by edsonrbispo** [comment]
Am I having the same problem, any solution?

**Comment by 0biWanKenobi** [comment]
my PR has been merged, so hopefully we'll get a new release soon 😎

**Comment by zachbroad** [comment]
Same on SDK version 30

**Comment by insinfo** [comment]
Am I having the same problem

```console
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.5\android\src\main\java\com\it_nomads\fluttersecurestorage\ciphers\RSACipher18Implementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [versÃ£o 10.0.19042.630], locale pt-BR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)
```

```yaml
name: riodasostrasapp
description: App Oficial da Prefeitura de Rio das Ostras
version: 1.0.2+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  connectivity: ^2.0.2
  url_launcher: ^5.7.10
  share: ^0.6.5+4
  map_launcher: ^1.0.0
  device_id: ^0.2.0
  device_info: ^1.0.0
  location_permissions: ^3.0.0+1
  location: ^3.1.0
  flutter_inappwebview: ^4.0.0+4

  #firebase services
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16

  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  flutter_advanced_networkimage: ^0.7.0
 
  #webview_flutter: ^0.3.22+1
  webview_flutter: ^1.0.7
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  queries: ^0.1.14
  #flutter_svg: ^0.17.4
  intl: ^0.16.1

  http: ^0.12.2
  dio: ^3.0.10
  universal_html: ^1.2.2
  essential_rest: ^1.1.22
  #wideget para infinit scroll
  incrementally_loading_listview: ^0.3.0
  
  #bloc state manager  
  flutter_bloc: ^4.0.0 #^3.2.0
  bloc: ^4.0.0
  #mobx state manager
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  #redux state manager
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  redux_thunk: ^0.3.0
  #provider state manager
  provider: ^4.1.2
  flutter_modular: ^2.0.1
  equatable: ^1.1.1

  carousel_slider: ^2.3.1
  #para armazenar o token  
  flutter_secure_storage: ^3.3.5
  #gerar codigo qr
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  jaguar_jwt: ^2.1.6

  riodasostrasapp_core:
    hosted:
      name: riodasostrasapp_core
      url: http://pub.riodasostras.rj.gov.br:4000
    version: ^1.0.39

dependency_overrides:
  rxdart: ^0.24.1
  #flutter_svg: ^0.19.2+1
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
  slidy: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700      
    - family: pmro_app
      fonts:
        - asset: assets/fonts/pmro.ttf         
     
   
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
      
```
