### ISSUE TITLE
Unable to ship with a snap version

### ISSUE THREAD

**Issue by ChristianPauly** [mogol/flutter_secure_storage#232]
Hello there the newest support for Linux has broken my snap version. The hints in the readme are not working for me. The package `libjsoncpp1-dev` can't be found. When I try it with `libjsoncpp-dev` or `libjsoncpp1` in the stage-packages I get this logs:
`/snap/famedly-desktop/x6/app: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory`

My snapcraft.yaml part looks like this:
```yaml
#...
base: core18
#...
  famedly-desktop:
    plugin: dump
    source: ./build/linux/release/bundle/
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsqlite3-dev
      - libsecret-1-dev
      - libjsoncpp-dev # which package is the correct one?
#...
apps:
  famedly-desktop:
    extensions: [flutter-stable]
```

I cant build it with snapcraft so I'm just packaging it with the dump plugin.
