### ISSUE TITLE
Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient

### ISSUE THREAD

**Issue by maxisme** [mogol/flutter_secure_storage#309]
Hello,

I am getting the error:
> Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.808" (uid=1000 pid=87036 comm="/snap/notifi/x13/bin/notifi " label="snap.notifi.notifi (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.24" (uid=1000 pid=3760 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

When doing:
```bash
git clone https://github.com/maxisme/notifi
cd notifi
git checkout linux
snapcraft
sudo snap install notifi_0.1.0_amd64.snap --dangerous && notifi
```

I was expecting adding `password-manager-service` to `apps.notifi.plugs` in my `snapcraft.yaml` but I am still getting the error unfortunately.

**Comment by maxisme** [comment]
https://forum.snapcraft.io/t/remote-error-from-secret-service-org-freedesktop-dbus-error-accessdenied-an-apparmor-policy-prevents-this-sender-from-sending-this-message-to-this-recipient/26508

**Comment by talhabalaj** [comment]
Here's my `snapcraft.yaml` that I used to test this plugin while building it.  There is no need for you add a dbus slot for this plugin to work. If it doesn't work after removing the dbus slot, follow this [solution](https://forum.snapcraft.io/t/help-my-flutter-app-is-taking-too-long-to-get-reviewed/22538/3?u=talhabalaj). 

```yaml
apps:
  uet-lms:
    command: uet_lms_app
    extensions: [flutter-dev]
    plugs:
    - network
    - mount-observe
    - x11
    - home
    - removable-media
    - browser-support
    - password-manager-service

parts:
  uet-lms:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
    - libsecret-1-dev
    - libjsoncpp-dev
    stage-packages:
    - libsecret-1-dev
    - libjsoncpp-dev
 ```
