### ISSUE TITLE
flutter_secure_storage does not work on Windows.

### ISSUE THREAD

**Issue by astudilloalex** [mogol/flutter_secure_storage#379]
Hello, the package show a error when try launch on Windows.

**Platform:** Windows
**Package version:** 5.0.2

This is my pubspec.yaml file:

```
name: pharmacy_billing_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  http: ^0.13.4
  responsive_design: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
```
Just declare the package, I'm not using it yet but I'm getting the following error.
```
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
[D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\windows\flutter\ephemeral\.plugin_symlinks\flutter_secure_storage_windows\windows\flutter_secure_storage_windows_plugin.cpp]()(6,10): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory [[D:\Users\Alex\Documents\FlutterProjects\pharmacy_billing_system\build\windows\plugins\flutter_secure_storage_windows\flutter_secure_storage_windows_plugin.vcxproj]()]
Exception: Build process failed.
Exited (sigterm)
```

![image](https://user-images.githubusercontent.com/48831301/157480476-ab171ab1-cb25-4ed1-8ccf-d4504e416cd5.png)

The software works fine if I remove the dependency from my pubspec.yaml.
