### ISSUE TITLE
macOS build fails with error cannot find GeneratedPluginRegistrant.swift:12:3

### ISSUE THREAD

**Issue by ptheofan** [mogol/flutter_secure_storage#486]
```
Building macOS application...
/Users/xxx/Sites/insta_sensors/macos/Flutter/GeneratedPluginRegistrant.swift:12:3: error: cannot find 'FlutterSecureStorageMacosPlugin' in scope
  FlutterSecureStorageMacosPlugin.register(with: registry.registrar(forPlugin: "FlutterSecureStorageMacosPlugin"))
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Am I doing something wrong or is it an issue with the latest XCode?

**Comment by valientegaston** [comment]
Same issue here

**Comment by Megamil** [comment]
I know it's not correct, but just to help temporarily, but just change from FlutterSecureStorageMacosPlugin to SwiftFlutterSecureStoragePlugin in the generated file in Flutter/GeneratedPluginRegistrant

**Comment by felipecastrosales** [comment]
Same problem here. :(

**Comment by juliansteenbakker** [comment]
Which version of flutter_secure_storage are you using?

**Comment by ptheofan** [comment]
Using the latest stable, version 7.0.0
These are the details in the .lock
```
  flutter_secure_storage:
    dependency: "direct main"
    description:
      name: flutter_secure_storage
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.0"
  flutter_secure_storage_linux:
    dependency: transitive
    description:
      name: flutter_secure_storage_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  flutter_secure_storage_macos:
    dependency: transitive
    description:
      name: flutter_secure_storage_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  flutter_secure_storage_platform_interface:
    dependency: transitive
    description:
      name: flutter_secure_storage_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  flutter_secure_storage_web:
    dependency: transitive
    description:
      name: flutter_secure_storage_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.1"
  flutter_secure_storage_windows:
    dependency: transitive
    description:
      name: flutter_secure_storage_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
```
