### ISSUE TITLE
flutter_secure_storage seems to not install in ios folder if there were existing pods.

### ISSUE THREAD

**Issue by BeStillAsBright** [mogol/flutter_secure_storage#57]
Hi! For whatever reason, there is nothing related to flutter_secure_storage in my ios folder of the overall app, not even in the Podfile. I'm wondering if this has to do with me already installing a pod into the project (I made a pod for a c library that I depend on) before/simultaneous with installing flutter_secure_storage?

Flutter doctor comes up clean as well.

```
Xcode build done.                                            2.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/mike/src/mobile/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'flutter_secure_storage/FlutterSecureStoragePlugin.h' file not found
    #import <flutter_secure_storage/FlutterSecureStoragePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] Connected device (1 available)

• No issues found!
```

```
~/src/mobile/ios(master ✗) ls Pods 
Headers              Manifest.lock        Target Support Files
Local Podspecs       Pods.xcodeproj
~/src/mobile/ios(master ✗) ls Pods/Target\ Support\ Files 
Pods-Runner mbedTLS
```

```
~/src/mobile/ios(master ✗) ls -la
total 24
drwxr-xr-x  11 mike  staff  352 Jun  3 15:16 .
drwxr-xr-x  18 mike  staff  576 Jun  3 15:16 ..
drwxr-xr-x   8 mike  staff  256 Jun  3 15:17 Flutter
drwxr-xr-x   2 mike  staff   64 Jun  3 11:01 Frameworks
-rw-r--r--@  1 mike  staff  292 Jun  3 11:15 Podfile
-rw-r--r--   1 mike  staff  284 Jun  3 11:15 Podfile.lock
drwxr-xr-x   7 mike  staff  224 Jun  3 15:02 Pods
drwxr-xr-x  10 mike  staff  320 Jun  2 16:26 Runner
drwxr-xr-x@  5 mike  staff  160 Jun  3 11:15 Runner.xcodeproj
drwxr-xr-x@  5 mike  staff  160 Jun  3 11:01 Runner.xcworkspace
-rw-r--r--   1 mike  staff   15 Jun  3 15:17 ServiceDefinitions.json
```

Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'mbedTLS', :path => '../Pods/mbedTLS'

  # Pods for Runner

end
```

So I'm wondering what I can do to get this configured to get the pod in correctly.

Thanks!
Mike

---

EDIT:
Here is my pubspec.yaml
```
name: mobile
description: A mobile frontend for my project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_secure_storage: ^3.2.1+1
  provider: ^2.0.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
